name: Build Engine
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    # nothing here
jobs:
  build-macos:
    strategy:
      fail-fast: true
      matrix:
        build_type: [Debug, Release]
        compiler: [clang]
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Install LLVM from Homebrew
        run: brew install llvm
      
      - name: Configure CMake
        run: ${{github.workspace}}/cmake_configure_macos.sh Makefiles
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
      
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChiraEngine-macOS-${{matrix.compiler}}-${{matrix.build_type}}
          path: |
            ${{github.workspace}}/build/resources/
            ${{github.workspace}}/build/ChiraEditor.app
            ${{github.workspace}}/build/*.dylib*
          retention-days: 1

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Necessary Packages
        run: sudo apt update && sudo apt install -y cmake build-essential xorg-dev mesa-common-dev mesa-utils

      - name: Install GCC
        if: ${{matrix.compiler == 'gcc'}}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 11
          platform: x64

      - name: Install Clang
        if: ${{matrix.compiler == 'clang'}}
        uses: egor-tensin/setup-clang@v1
        with:
          version: 13
          platform: x64

      - name: Configure CMake
        run: cmake -G "Unix Makefiles" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChiraEngine-Linux-${{matrix.compiler}}-${{matrix.build_type}}
          path: |
            ${{github.workspace}}/build/resources/
            ${{github.workspace}}/build/ChiraEditor
            ${{github.workspace}}/build/*.so*
          retention-days: 1

  build-mingw:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER="/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="/mingw64/bin/g++.exe"

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}

    - name: Copy Necessary DLLs
      run: |
        cp /mingw64/bin/libgcc_s_seh-1.dll build/libgcc_s_seh-1.dll
        cp /mingw64/bin/libstdc++-6.dll    build/libstdc++-6.dll

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ChiraEngine-Windows-mingw64-${{matrix.build_type}}
        path: |
            ${{github.workspace}}/build/resources/
            ${{github.workspace}}/build/ChiraEditor.exe
            ${{github.workspace}}/build/*.dll
        retention-days: 1

  build-msvc:
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          spectre: true

      - name: Configure CMake
        run: cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ChiraEngine-Windows-msvc-${{matrix.build_type}}
          path: |
            ${{github.workspace}}/build/resources/
            ${{github.workspace}}/build/ChiraEditor.exe
            ${{github.workspace}}/build/*.dll
          retention-days: 1
